apiVersion: apps/v1
kind: Deployment
metadata:
  name: wingman-api
  labels:
    app: wingman-api
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wingman-api
  template:
    metadata:
      labels:
        app: wingman-api
        component: api
    spec:
      containers:
      - name: wingman-api
        image: 264765154707.dkr.ecr.us-east-1.amazonaws.com/wingman-api:dev
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "info"
        - name: API_VERSION
          value: "v1"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi