apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: wingman-api

images:
- name: 264765154707.dkr.ecr.us-east-1.amazonaws.com/wingman-api
  newTag: dev