# eksctl cluster configuration for nonprod (shared dev/qa)
# Creates cluster: cluckn-bell-nonprod
# Account: 264765154707 (cluckin-bell-qa)
# Region: us-east-1
# Kubernetes version: 1.33
# Node groups: dev (dev workloads), qa (qa workloads)

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluckn-bell-nonprod
  region: us-east-1
  version: "1.33"
  tags:
    Project: cluckn-bell
    Environment: nonprod
    ManagedBy: eksctl

# VPC Configuration
# Use existing VPC created by Terraform (cb-devqa-use1)
# Private subnets: 10.60.1.0/24, 10.60.2.0/24, 10.60.3.0/24
vpc:
  id: vpc-0749517f2c92924a5  # Replace with actual VPC ID from terraform output
  subnets:
    private:
      us-east-1a:
        id: subnet-0d1a90b43e2855061  # Replace with actual private subnet ID
      us-east-1b:
        id: subnet-0e408dd3b79d3568b  # Replace with actual private subnet ID
      us-east-1c:
        id: subnet-00d5249fbe0695848  # Replace with actual private subnet ID

# IAM Configuration
iam:
  withOIDC: true
  serviceAccounts: []

# Managed Node Groups
managedNodeGroups:
  # Dev node group for dev environment workloads
  - name: dev
    instanceType: m7i.large
    amiFamily: AmazonLinux2023
    minSize: 1
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 50
    volumeType: gp3
    privateNetworking: true
    labels:
      environment: dev
      role: application
      nodegroup: dev
    tags:
      Name: cluckn-bell-nonprod-dev
      Environment: dev
      NodeGroup: dev
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluckn-bell-nonprod: "owned"
      karpenter.sh/discovery: cluckn-bell-nonprod
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: false
        certManager: false
        appMesh: false
        ebs: true
        efs: true
        albIngress: false
        xRay: false
        cloudWatch: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  # QA node group for qa environment workloads  
  - name: qa
    instanceType: m7i.large
    amiFamily: AmazonLinux2023
    minSize: 1
    maxSize: 8
    desiredCapacity: 3
    volumeSize: 50
    volumeType: gp3
    privateNetworking: true
    labels:
      environment: qa
      role: application
      nodegroup: qa
    tags:
      Name: cluckn-bell-nonprod-qa
      Environment: qa
      NodeGroup: qa
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluckn-bell-nonprod: "owned"
      karpenter.sh/discovery: cluckn-bell-nonprod
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: false
        certManager: false
        appMesh: false
        ebs: true
        efs: true
        albIngress: false
        xRay: false
        cloudWatch: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

# Add-ons (managed by AWS)
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
    wellKnownPolicies:
      ebsCSIController: true
  - name: eks-pod-identity-agent
    version: latest

# CloudWatch logging
cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
    logRetentionInDays: 7
