apiVersion: apps/v1
kind: Deployment
metadata:
  name: wingman-api
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: wingman-api
        env:
        - name: NODE_ENV
          value: "staging"
        - name: LOG_LEVEL
          value: "info"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
