name: IaC Security (tfsec)

on:
  pull_request:
    branches: [ "develop", "staging", "main" ]

permissions:
  contents: read

jobs:
  tfsec:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v2
        with:
          format: sarif
          additional_args: "--soft-fail"
      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
