name: Terraform Dev

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply changes (true to apply, false to plan only)"
        required: true
        default: "false"
        type: choice
        options: ["false", "true"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      working_directory: "stacks/bootstrap"
      aws_region: "us-east-1"
      apply: ${{ inputs.apply == 'true' }}
      var_file: "../../env/dev.tfvars"
    secrets:
      terraform_role_arn: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}